export const scenarioCommands = [
  "state-ui-action",
  "state-content-action",
  "state-client-cleanup",
  "relay-register",
  "relay-policy-mode",
  "relay-local-call",
  "relay-call",
  "relay-old-call",
  "relay-refresh",
  "relay-fresh-call",
  "background-summary",
  "background-increment",
  "background-setting",
  "background-set-setting",
  "content-connect",
  "content-identity",
  "content-echo",
  "content-hold",
  "content-fail",
  "select-start",
  "provider-cardinality",
  "select-session",
  "create-frame",
  "create-document",
  "create-concurrent",
  "pre-ready-close",
  "multicast-create",
  "multicast-select",
  "reference-callback",
  "capability-retain",
  "capability-invoke",
  "capability-release",
  "identity-pinned",
  "multicast-bound-invoke",
  "multicast-rebind",
  "multicast-fail",
  "multicast-unavailable",
  "registry-facts",
  "identity-select-beta",
  "identity-constraint",
  "identity-update",
  "worker-facts",
  "worker-pending",
  "offscreen-create",
  "offscreen-close",
  "policy-deny",
  "policy-allow",
  "abort-acquire",
  "security-counter",
  "worker-proxy-retain",
  "worker-proxy-invoke",
  "worker-proxy-fresh",
  "worker-state-retain",
  "worker-state-write",
  "worker-state-status",
  "worker-state-fresh",
  "worker-state-cleanup",
  "worker-storage-write",
  "worker-storage-read",
  "worker-capability-retain",
  "worker-capability-invoke",
  "worker-capability-release",
  "worker-capability-fresh",
  "worker-capability-fresh-release",
  "worker-capability-fresh-invoke",
  "worker-state-check",
  "provider-first-select",
  "capability-proxy-invoke",
  "capability-reference-invoke",
  "document-route-facts",
  "pre-ready-port-close",
] as const;

export type ScenarioCommand = (typeof scenarioCommands)[number];

export const isScenarioCommand = (
  command: string,
): command is ScenarioCommand =>
  (scenarioCommands as readonly string[]).includes(command);
